conturo-prototyping/pack-ship-client

src/common/Button.jsx, src/shipping_queue/ShippingQueue.jsx
I think this is about what the issue is detailing. Let me know if you would like it to look a little differently.
=> Restyled clear and search buttons

src/router/router.jsx
=> Auth on location change

src/common/CircularProgress.jsx, src/components/OrderAndPartSearchBar.jsx, src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/HistoryTable.jsx, src/packing_queue/tables/PackingQueueTable.jsx, src/packing_queue/utils/historyDetails.js, src/packing_queue/utils/sortModelFunctions.js, src/router/router.jsx, src/services/server.js, src/shipping_queue/ShippingQueue.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx, src/shipping_queue/utils/sortModelFunctions.js
There is quite a few changes here you may want to test this one extra.
You will need https://github.com/conturo-prototyping/pack-ship-server/pull/12 merged first.
1. Fixed some warnings.
2. OrderAndSearchBar added
3. histSearch is hit so this fixes #17 (please confirm)
4. some code formatting
=> 13 order part search

src/packing_queue/tables/HistoryTable.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx
Needed to better handle https://github.com/conturo-prototyping/pack-ship-server/pull/13
Closes #40 
It also applies the same logic to the shipments
=> Changed from delete on confirm to delete on submit

src/components/OrderAndPartSearchBar.jsx, src/components/Tabs.jsx, src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/HistoryTable.jsx, src/packing_queue/tables/PackingQueueTable.jsx, src/shipping_queue/ShippingQueue.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx, src/utils/Constants.js
=> Added consistent layout for pages

src/packing_queue/tables/HistoryTable.jsx
=> added dest col history packing slip

src/shipping_queue/tables/ShippingHistoryTable.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx, src/shipping_queue/utils/historyDetails.js
=> added dest cols to the shipment tabs

src/shipping_queue/tables/ShippingQueueTable.jsx
=> restrict selecting different dest on ship queue

src/edit_packing_slip/EditPackingSlipDialog.jsx, src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/HistoryTable.jsx, src/packing_slip/PackingSlipDialog.jsx, src/packing_slip/components/DestinationToggle.jsx, src/services/server.js
=> added toggle button for destination

src/packing_queue/tables/HistoryTable.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx, src/shipping_queue/utils/historyDetails.js
merge target does not appear to reflect branch changes
=> Revert 58 50 diable mixing dest types

src/create_shipment/CreateShipmentDialog.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx
=> display dest in create ship dialog

src/components/OrderAndPartSearchBar.jsx, src/components/Search.jsx, src/components/TextInput.jsx, src/packing_queue/PackingQueue.jsx, src/shipping_queue/ShippingQueue.jsx
=> Autofocus search fields

src/components/TextInput.jsx, src/components/TitleTextInput.jsx, src/services/server.js, src/shipping_queue/EditShipmentDialog.jsx, src/shipping_queue/ShipmentDetails.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx
Added shipping address on vendor destination shipments
=> add shipping address

src/components/TextInput.jsx, src/create_shipment/CreateShipmentDialog.jsx, src/create_shipment/components/CreateShipmentInfoForm.jsx, src/create_shipment/components/ShippingAddressForm.jsx, src/create_shipment/constants/ShippingDialogConstants.js, src/services/server.js, src/shipping_queue/tables/ShippingQueueTable.jsx, src/utils/Constants.js
=> 51 new shipment flow

src/packing_queue/PackingQueue.jsx
=> 67 vendor update fix

src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/PackingQueueTable.jsx, src/shipping_queue/ShippingQueue.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx
just re-did what jon did on
https://github.com/conturo-prototyping/pack-ship-client/pull/71
i accidentally deleted the destination branch before merging that PR so
it got stuck in limbo
=> clean up console warnings

src/create_shipment/CreateShipmentDialog.jsx, src/create_shipment/components/CreateShipmentTable.jsx, src/shipping_queue/PackingSlipDropdown.jsx, src/shipping_queue/tables/ShipQueuePackSlipDropdown.jsx
=> Added Batch Number

src/packing_queue/tables/HistoryTable.jsx, src/services/server.js, src/shipping_queue/tables/ShippingHistoryTable.jsx
Closes #75 
Solution:
* Created new `downloadShipmentPDF` in server.js file
* Created `Download` menu button on shipments history page that used new `createShipmentPdfDoc` function. 
* Commented out code for download button on packing slip history page.
=> 75 move download button to packing

src/shipping_queue/tables/ShipQueuePackSlipDropdown.jsx
@jarrilla, sorry about that. Not sure when that got removed. Check this out and let me know. closes #85
=> added packQty

src/components/CheckboxColumn.jsx, src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/PackingQueueTable.jsx
closes #76 
@jarrilla, this one was more involved than at first glance. Check this one out and make sure I covered it all.
The bug is fixed. I also added the last thing we chated about. So now, the checked row will take priority but when it is unchecked, it will be removed if other search criteria happen to filter that row out.
=> Fulfilled check bug fix

src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/PackingQueueTable.jsx, src/packing_slip/PackingSlipDialog.jsx, src/services/server.js
Closes #86 
@jarrilla I wasn't sure exactly how to get a non-default CUSTOMER field in the destination block since it seems to be populating on several fields and the reset API call isn't populating that. I was also running into an issue when creating a new packing slip where the fulfilled qty wasn't getting updated on the work order. After some investigation, I believe this is a backend issue as the data isn't coming back filled in even when the packing slip makes it to the shipment tab. 
Let me know your thoughts.
=> Added destination column and filtering checks based on it

src/packing_queue/tables/HistoryTable.jsx, src/shipping_queue/tables/ShippingHistoryTable.jsx
closes #83 
Solution: 
* Added `Download` menu item and corresponding `onDownloadPDFClick` function. 
Notes: 
* Updated to display success message on successful completion of `createShipmentPdfDoc`
=> 83 add download button to packing slips

src/packing_queue/PackingQueue.jsx, src/receiving_queue/ReceivingQueue.jsx, src/receiving_queue/ReceivingQueueDropdown.jsx, src/receiving_queue/tables/ReceivingQueueTable.jsx, src/router/NavigationBar.js, src/router/router.jsx, src/services/server.js, src/shipping_queue/ShippingQueue.jsx, src/themes/base.js, src/themes/receivingTheme.js
Leaving this as draft as no data is coming in yet. This allows other branches to be made off of it since the common functionality and classes are there.
=> Initial commit of grid layout and class setup

src/edit_packing_slip/EditPackingSlipDialog.jsx, src/packing_queue/PackingQueue.jsx, src/packing_queue/tables/HistoryTable.jsx, src/packing_queue/utils/sortModelFunctions.js, src/services/server.js, src/shipping_queue/EditShipmentDialog.jsx, src/shipping_queue/PackingSlipDropdown.jsx, src/shipping_queue/ShippingQueue.jsx, src/shipping_queue/tables/ShipQueuePackSlipDropdown.jsx, src/shipping_queue/tables/ShippingQueueTable.jsx
This requires https://github.com/conturo-prototyping/pack-ship-server/pull/67
=> Packing slip id to label

src/packing_queue/PackingQueue.jsx, src/receive_shipment/ReceiveShipmentDialog.jsx, src/receive_shipment/components/ReceiveShipmentTable.jsx, src/receiving_queue/ReceivingQueue.jsx, src/receiving_queue/tables/ReceivingQueueTable.jsx
qtyReceived is 0 by default and right justified like the other number columns.
I also fixed a few other bugs where ? was needed on accessing properties on objects. 
EDIT
this will fix https://linear.app/conturo-prototyping/issue/PS-38/auto-focus-first-line-of-an-incoming-delivery-when-receiving as well
=> default qtyRecevied to 0

src/receiving_queue/ReceivingQueue.jsx
This MR currently doesn't have error checking on the date picker, but I believe none of them do. I am tackling it in a separate MR so that this can unblock other issues and be used.
=> Fe edit received shipment1 ie receiving ps 40

src/shipping_queue/tables/ShippingPendingTable.jsx
=> set selected shipment correctly

src/packing_queue/tables/PendingTable.jsx, src/shipping_queue/tables/ShippingPendingTable.jsx
use custom comparator for date-created on pending tabs
=> Pending tab date created sort fix
